name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        # Latest minor release of Go 1.19:
        go-version: ^1.19

    - name: Ensure all files were formatted as per gofmt
      if: matrix.os == 'ubuntu-latest'
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]

    - name: install rsync
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker build --pull --no-cache --rm -t=rsync-debian -f testdata/ci-debian.Dockerfile .
        docker build --pull --no-cache --rm -t=rsync-fedora -f testdata/ci-fedora.Dockerfile .

    - name: install rsync
      if: matrix.os == 'windows-latest'
      run: choco install rsync

    - name: run tests (linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        go test -v ./internal/... && go test -c
        echo "::group::rsync from Debian"
        docker run -v $PWD:/usr/src/rsync/ -w /usr/src/rsync rsync-debian ./rsync.test -test.v
        echo "::endgroup::"
        echo "::group::rsync from Fedora"
        docker run -v $PWD:/usr/src/rsync/ -w /usr/src/rsync rsync-fedora ./rsync.test -test.v
        echo "::endgroup::"

    - name: run tests (macos)
      if: matrix.os == 'macos-latest'
      run: go test -v ./internal/... && go test -c && sudo ./rsync.test -test.v

    - name: run tests (windows)
      if: matrix.os == 'windows-latest'
      run: go install ./cmd/...
